[build]
  command = "npm run build"
  functions = "netlify-functions"
  publish = "out"  # or "build" depending on your framework

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200